name: Build, Deploy, and Update Kubernetes on AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP_NAME: deepak-rg
      AKS_CLUSTER_NAME: azure-aks-deep34

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install
        working-directory: javapack

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: javapack
          file: javapack/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.run_number }}
            ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $AKS_CLUSTER_NAME --overwrite-existing

      - name: Update Kubernetes deployment
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}|g" manifest/deployment.yaml
          kubectl apply -f manifest/deployment.yaml
          kubectl apply -f manifest/service.yaml
